public enum State {
    NONE,
    SIGN_UP,
    PRESS_ADD_RECEIPT,
    WAIT_PHOTO,
    WAIT_CHECK_RECEIPT,
    FAIL_CHECK_RECEIPT,
    VIEW_RECEIPTS,
    VIEW_STATISTIC,
    VIEW_AUTHORS,
    CHOOSE_COMMAND,
    NOTIFY_MADE_RECEIPT
}
